fix: return exit code 0 from pytest when no fuzzing tests are collected in CI
When fuzzing tests exist and are all passing, we get exit code 0:

    $ ./run.sh
    .
    === 1 passed in 1.75s ===

    $ echo $?
    0

When fuzzing tests exist and are failing, we get the underlying non-zero exit code:

    $ ./run.sh
    F
    === FAILURES ===
    ___ test_foo ___
    [gw0] linux -- Python 3.8.5 ./eip712_env_2/bin/python3
    E   hypothesis.errors.MultipleFailures: Hypothesis found 2 distinct failures.
    [...]
    === short test summary info ===
    FAILED tests/test_messages.py::test_foo - hypothesis.errors.MultipleFailures: Hypothesis found 2 distinct failures.
    === 1 failed in 1.66s ===

    $ echo $?
    1

When fuzzing tests don't exist, instead of getting a non-zero exit code of 5 (which causes CI jobs to fail), we get a successful exit code of 0:

    $ ./run.sh
    === no tests ran in 1.53s ===
    No tests marked with 'fuzzing' were found.

    $ echo $?
    0